import io
import json
import re
from datetime import datetime
from fastapi import APIRouter, Header, HTTPException, Query
from fastapi.responses import StreamingResponse
from api.db import query_one
from api.routes.auth import get_session

router = APIRouter()

BRAND_GREEN = "0B4B2A"
BRAND_GREEN_LIGHT = "2E7D4F"
DISCLAIMER_AR = "هذه الدراسة القانونية تم توليدها بواسطة نظام الباحث. مسؤولية التحقق من صحة المعلومات والوقائع تقع على المستخدم."
DISCLAIMER_EN = "This legal study was generated by Albaheth AI system. The user is responsible for verifying the accuracy of all information and facts."


def _get_user_from_auth(authorization: str | None, token: str | None = None) -> int | None:
    raw = token or authorization
    if not raw:
        return None
    raw = raw.replace("Bearer ", "")
    session = get_session(raw)
    return session["user_id"] if session else None


def _get_study(study_id: int, user_id: int) -> dict:
    row = query_one(
        "SELECT id, query, content, citations, created_at FROM legal_studies WHERE id = %s AND user_id = %s;",
        [study_id, user_id],
    )
    if not row:
        raise HTTPException(status_code=404, detail="الدراسة غير موجودة")
    result = dict(row)
    if isinstance(result.get("citations"), str):
        result["citations"] = json.loads(result["citations"])
    return result


def _reshape_arabic(text: str) -> str:
    """Reshape Arabic letters for connected glyph rendering (no bidi reversal)."""
    try:
        import arabic_reshaper
        reshaped = arabic_reshaper.reshape(text)
        return reshaped
    except Exception:
        return text


def _shape_for_pdf(text: str) -> str:
    """Reshape Arabic and apply bidi for PDF canvas drawing (not for Paragraph)."""
    try:
        import arabic_reshaper
        from bidi.algorithm import get_display
        reshaped = arabic_reshaper.reshape(text)
        return get_display(reshaped)
    except Exception:
        return text


def _strip_markdown(text: str) -> str:
    """Remove markdown markers from text for plain rendering."""
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
    text = re.sub(r'\*(.+?)\*', r'\1', text)
    text = re.sub(r'#{1,6}\s+', '', text)
    text = re.sub(r'`(.+?)`', r'\1', text)
    return text


def _is_heading(line: str) -> bool:
    return bool(re.match(r'^#{1,6}\s+', line.strip()))


def _is_numbered_heading(line: str) -> bool:
    return bool(re.match(r'^\d+\.\s+', line.strip()))


def _is_bold_line(line: str) -> bool:
    stripped = line.strip()
    return stripped.startswith('**') and stripped.endswith('**') and len(stripped) > 4


def _format_citation(i: int, cite: dict) -> str:
    """Format a citation the same way the webpage does."""
    text = (
        f"{i+1}. رقم الحكم: {cite.get('judgment_number', 'غير محدد')} — "
        f"المحكمة: {cite.get('court_type', '')} {cite.get('court_level', '')} — "
        f"المدينة: {cite.get('city', '')}"
    )
    if cite.get("case_number"):
        text += f" | رقم القضية: {cite['case_number']}/{cite.get('case_year', '')}"
    if cite.get("judgment_date_hijri"):
        text += f" | تاريخ الحكم: {cite['judgment_date_hijri']}"
    return text


# ============================================================
# DOCX Export
# ============================================================
@router.get("/legal-study/{study_id}/export/docx")
def export_docx(study_id: int, authorization: str = Header(None), token: str = Query(None)):
    """Export a legal study as a Word document with Albaheth branding."""
    user_id = _get_user_from_auth(authorization, token)
    if not user_id:
        raise HTTPException(status_code=401, detail="غير مصرح")

    study = _get_study(study_id, user_id)

    try:
        from docx import Document
        from docx.shared import Pt, Inches, RGBColor, Cm
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.oxml.ns import qn
    except ImportError:
        raise HTTPException(status_code=500, detail="python-docx not installed")

    doc = Document()

    style = doc.styles['Normal']
    font = style.font
    font.name = 'Arial'
    font.size = Pt(12)
    # Set Normal style to RTL
    style_pPr = style.element.get_or_add_pPr()
    style_bidi = style_pPr.makeelement(qn('w:bidi'), {})
    style_pPr.append(style_bidi)

    for section in doc.sections:
        section.left_margin = Cm(2.5)
        section.right_margin = Cm(2.5)
        section.top_margin = Cm(2.5)
        section.bottom_margin = Cm(2.5)
        # Set section to RTL
        sectPr = section._sectPr
        bidi = sectPr.makeelement(qn('w:bidi'), {})
        sectPr.append(bidi)

    def _set_rtl(paragraph):
        """Set paragraph to RTL."""
        pPr = paragraph._p.get_or_add_pPr()
        bidi = pPr.makeelement(qn('w:bidi'), {})
        pPr.append(bidi)

    def _set_run_rtl(run):
        """Set run to RTL."""
        rPr = run._r.get_or_add_rPr()
        rtl = rPr.makeelement(qn('w:rtl'), {})
        rPr.append(rtl)

    def _add_arabic_run(paragraph, text, size=12, color=None, bold=False, italic=False):
        """Add a run with RTL flag and proper Arabic font."""
        run = paragraph.add_run(text)
        run.font.size = Pt(size)
        if color:
            run.font.color.rgb = color
        run.bold = bold
        run.italic = italic
        _set_run_rtl(run)
        return run

    GREEN = RGBColor(0x0B, 0x4B, 0x2A)
    GREEN_LIGHT = RGBColor(0x2E, 0x7D, 0x4F)
    MUTED = RGBColor(0x65, 0x75, 0x6B)

    # Header
    header = doc.sections[0].header
    header_para = header.paragraphs[0]
    header_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _add_arabic_run(header_para, "الباحث — Albaheth", size=14, color=GREEN, bold=True)

    # Title
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_rtl(title)
    _add_arabic_run(title, "دراسة قانونية", size=22, color=GREEN, bold=True)

    # Subtitle
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_rtl(subtitle)
    _add_arabic_run(subtitle, f"الموضوع: {study['query']}", size=14, color=GREEN_LIGHT, bold=True)

    # Date
    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_rtl(date_para)
    created = study.get("created_at", "")
    if hasattr(created, "strftime"):
        date_str = created.strftime("%Y-%m-%d %H:%M")
    else:
        date_str = str(created)
    _add_arabic_run(date_para, f"التاريخ: {date_str}", size=10, color=MUTED)

    doc.add_paragraph()

    # Content
    content = study["content"]
    for line in content.split("\n"):
        line = line.strip()
        if not line:
            continue

        p = doc.add_paragraph()
        _set_rtl(p)

        if _is_heading(line):
            p.alignment = WD_ALIGN_PARAGRAPH.LEFT
            _add_arabic_run(p, _strip_markdown(line), size=14, color=GREEN, bold=True)
        elif _is_numbered_heading(line):
            p.alignment = WD_ALIGN_PARAGRAPH.LEFT
            clean = re.sub(r'^\d+\.\s+', '', line)
            parts = re.split(r'(\*\*.+?\*\*)', clean)
            for part in parts:
                if part.startswith('**') and part.endswith('**'):
                    _add_arabic_run(p, _strip_markdown(part), size=13, color=GREEN, bold=True)
                else:
                    _add_arabic_run(p, part, size=13, color=GREEN, bold=True)
        elif _is_bold_line(line):
            p.alignment = WD_ALIGN_PARAGRAPH.LEFT
            _add_arabic_run(p, _strip_markdown(line), size=12, color=GREEN_LIGHT, bold=True)
        else:
            p.alignment = WD_ALIGN_PARAGRAPH.LEFT
            parts = re.split(r'(\*\*.+?\*\*)', line)
            for part in parts:
                if part.startswith('**') and part.endswith('**'):
                    _add_arabic_run(p, _strip_markdown(part), size=12, bold=True)
                else:
                    _add_arabic_run(p, part, size=12)

    # Citations
    doc.add_paragraph()
    citations_heading = doc.add_paragraph()
    _set_rtl(citations_heading)
    citations_heading.alignment = WD_ALIGN_PARAGRAPH.LEFT
    _add_arabic_run(citations_heading, "الأحكام المرجعية", size=16, color=GREEN, bold=True)

    for i, cite in enumerate(study.get("citations", [])):
        p = doc.add_paragraph()
        _set_rtl(p)
        p.alignment = WD_ALIGN_PARAGRAPH.LEFT
        _add_arabic_run(p, _format_citation(i, cite), size=10, color=MUTED)

    # Disclaimer
    doc.add_paragraph()
    disclaimer_heading = doc.add_paragraph()
    _set_rtl(disclaimer_heading)
    disclaimer_heading.alignment = WD_ALIGN_PARAGRAPH.LEFT
    _add_arabic_run(disclaimer_heading, "إخلاء مسؤولية", size=12, color=GREEN, bold=True)

    p = doc.add_paragraph()
    _set_rtl(p)
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    _add_arabic_run(p, DISCLAIMER_AR, size=10, color=MUTED, italic=True)

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _add_arabic_run(p, DISCLAIMER_EN, size=9, color=MUTED, italic=True)

    # Footer
    footer = doc.sections[0].footer
    footer_para = footer.paragraphs[0]
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer_para.add_run("Albaheth — AI-Powered Legal Research | albaheth.app")
    run.font.size = Pt(8)
    run.font.color.rgb = GREEN

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)

    filename = f"legal_study_{study_id}.docx"
    return StreamingResponse(
        buffer,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


# ============================================================
# PDF Export — uses WeasyPrint (HTML to PDF) with native Arabic RTL support
# ============================================================
@router.get("/legal-study/{study_id}/export/pdf")
def export_pdf(study_id: int, authorization: str = Header(None), token: str = Query(None)):
    """Export a legal study as a PDF with Albaheth branding."""
    user_id = _get_user_from_auth(authorization, token)
    if not user_id:
        raise HTTPException(status_code=401, detail="غير مصرح")

    study = _get_study(study_id, user_id)

    try:
        from weasyprint import HTML
    except ImportError:
        raise HTTPException(status_code=500, detail="weasyprint not installed")

    created = study.get("created_at", "")
    if hasattr(created, "strftime"):
        date_str = created.strftime("%Y-%m-%d %H:%M")
    else:
        date_str = str(created)

    # Build HTML content — same format as webpage
    content = study["content"]
    body_parts = []
    for line in content.split("\n"):
        line = line.strip()
        if not line:
            continue
        if _is_heading(line):
            body_parts.append(f'<h3 style="color:#0B4B2A;font-size:14pt;font-weight:bold;margin-top:12px;margin-bottom:6px;">{_strip_markdown(line)}</h3>')
        elif _is_numbered_heading(line):
            clean = _strip_markdown(line)
            body_parts.append(f'<h3 style="color:#0B4B2A;font-size:13pt;font-weight:bold;margin-top:12px;margin-bottom:6px;">{clean}</h3>')
        elif _is_bold_line(line):
            body_parts.append(f'<p style="color:#2E7D4F;font-size:12pt;font-weight:bold;margin:4px 0;">{_strip_markdown(line)}</p>')
        else:
            # Handle inline bold
            html_line = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', line)
            body_parts.append(f'<p style="font-size:12pt;line-height:1.6;margin-bottom:8px;text-align:justify;">{html_line}</p>')

    body_html = "\n".join(body_parts)

    # Citations HTML
    citations_html = ""
    for i, cite in enumerate(study.get("citations", [])):
        text = _format_citation(i, cite)
        citations_html += f'<p style="font-size:10pt;color:#65756B;margin-bottom:4px;padding-right:20px;">{text}</p>\n'

    # Full HTML document with RTL and Arabic font
    html = f"""<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
<meta charset="utf-8">
<style>
  @page {{
    size: A4;
    margin: 2.5cm;
    @bottom-center {{
      content: "Albaheth — AI-Powered Legal Research | albaheth.app";
      font-size: 8pt;
      color: #0B4B2A;
    }}
  }}
  body {{
    direction: rtl;
    font-family: "Arial", "Helvetica", sans-serif;
    font-size: 12pt;
    color: #333;
  }}
  .header {{
    text-align: center;
    border-bottom: 2px solid #0B4B2A;
    padding-bottom: 10px;
    margin-bottom: 20px;
  }}
  .header h1 {{
    color: #0B4B2A;
    font-size: 14pt;
    margin: 0;
  }}
  .title {{
    text-align: center;
    font-size: 22pt;
    color: #0B4B2A;
    font-weight: bold;
    margin-bottom: 4px;
  }}
  .subtitle {{
    text-align: center;
    font-size: 14pt;
    color: #2E7D4F;
    font-weight: bold;
    margin-bottom: 4px;
  }}
  .date {{
    text-align: center;
    font-size: 10pt;
    color: #65756B;
    margin-bottom: 20px;
  }}
  .citations-heading {{
    color: #0B4B2A;
    font-size: 16pt;
    font-weight: bold;
    margin-top: 20px;
    margin-bottom: 8px;
  }}
  .disclaimer-heading {{
    color: #0B4B2A;
    font-size: 12pt;
    font-weight: bold;
    margin-top: 20px;
    margin-bottom: 6px;
  }}
  .disclaimer-ar {{
    font-size: 10pt;
    color: #65756B;
    font-style: italic;
    text-align: justify;
    margin-bottom: 4px;
  }}
  .disclaimer-en {{
    font-size: 9pt;
    color: #65756B;
    font-style: italic;
    text-align: center;
  }}
</style>
</head>
<body>
  <div class="header">
    <h1>الباحث — Albaheth</h1>
  </div>
  <div class="title">دراسة قانونية</div>
  <div class="subtitle">الموضوع: {study['query']}</div>
  <div class="date">التاريخ: {date_str}</div>

  {body_html}

  <div class="citations-heading">الأحكام المرجعية</div>
  {citations_html}

  <div class="disclaimer-heading">إخلاء مسؤولية</div>
  <p class="disclaimer-ar">{DISCLAIMER_AR}</p>
  <p class="disclaimer-en">{DISCLAIMER_EN}</p>
</body>
</html>"""

    buffer = io.BytesIO()
    HTML(string=html).write_pdf(buffer)
    buffer.seek(0)

    filename = f"legal_study_{study_id}.pdf"
    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
